
package com.woniu.sncp.webservice.usercenter.query;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "QueryWebServicePortType", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QueryWebServicePortType {


    /**
     * 
     * @param in6
     * @param in5
     * @param in8
     * @param in7
     * @param in9
     * @param in10
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
    @RequestWrapper(localName = "queryImprestBySubid", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryImprestBySubid")
    @ResponseWrapper(localName = "queryImprestBySubidResponse", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryImprestBySubidResponse")
    public String queryImprestBySubid(
        @WebParam(name = "in0", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        int in4,
        @WebParam(name = "in5", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        long in5,
        @WebParam(name = "in6", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        int in6,
        @WebParam(name = "in7", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        int in7,
        @WebParam(name = "in8", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        int in8,
        @WebParam(name = "in9", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in9,
        @WebParam(name = "in10", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in10);

    /**
     * 
     * @param in6
     * @param in5
     * @param in8
     * @param in7
     * @param in9
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
    @RequestWrapper(localName = "queryRegisterByAccountByDate", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryRegisterByAccountByDate")
    @ResponseWrapper(localName = "queryRegisterByAccountByDateResponse", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryRegisterByAccountByDateResponse")
    public String queryRegisterByAccountByDate(
        @WebParam(name = "in0", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        int in4,
        @WebParam(name = "in5", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in6,
        @WebParam(name = "in7", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        int in7,
        @WebParam(name = "in8", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in8,
        @WebParam(name = "in9", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in9);

    /**
     * 
     * @param in6
     * @param in5
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
    @RequestWrapper(localName = "querySql", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QuerySql")
    @ResponseWrapper(localName = "querySqlResponse", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QuerySqlResponse")
    public String querySql(
        @WebParam(name = "in0", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in4,
        @WebParam(name = "in5", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in6);

    /**
     * 
     * @param in6
     * @param in5
     * @param in8
     * @param in7
     * @param in9
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "queryPayOrderByDate10mins")
    @WebResult(name = "out", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
    @RequestWrapper(localName = "queryPayOrderByDate10mins", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryPayOrderByDate10Mins")
    @ResponseWrapper(localName = "queryPayOrderByDate10minsResponse", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryPayOrderByDate10MinsResponse")
    public String queryPayOrderByDate10Mins(
        @WebParam(name = "in0", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        long in4,
        @WebParam(name = "in5", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in6,
        @WebParam(name = "in7", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        int in7,
        @WebParam(name = "in8", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in8,
        @WebParam(name = "in9", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in9);

    /**
     * 
     * @param in6
     * @param in5
     * @param in8
     * @param in7
     * @param in9
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
    @RequestWrapper(localName = "queryImprestOrderByDate", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryImprestOrderByDate")
    @ResponseWrapper(localName = "queryImprestOrderByDateResponse", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryImprestOrderByDateResponse")
    public String queryImprestOrderByDate(
        @WebParam(name = "in0", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        long in4,
        @WebParam(name = "in5", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in6,
        @WebParam(name = "in7", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        int in7,
        @WebParam(name = "in8", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in8,
        @WebParam(name = "in9", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in9);

    /**
     * 
     * @param in5
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
    @RequestWrapper(localName = "queryIssuerListByArea", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryIssuerListByArea")
    @ResponseWrapper(localName = "queryIssuerListByAreaResponse", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryIssuerListByAreaResponse")
    public String queryIssuerListByArea(
        @WebParam(name = "in0", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in4,
        @WebParam(name = "in5", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in5);

    /**
     * 
     * @param in6
     * @param in5
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
    @RequestWrapper(localName = "queryRegCount", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryRegCount")
    @ResponseWrapper(localName = "queryRegCountResponse", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryRegCountResponse")
    public String queryRegCount(
        @WebParam(name = "in0", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        long in3,
        @WebParam(name = "in4", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        int in4,
        @WebParam(name = "in5", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in6);

    /**
     * 
     * @param in6
     * @param in5
     * @param in8
     * @param in7
     * @param in9
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "queryImprestOrderByDate10mins")
    @WebResult(name = "out", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
    @RequestWrapper(localName = "queryImprestOrderByDate10mins", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryImprestOrderByDate10Mins")
    @ResponseWrapper(localName = "queryImprestOrderByDate10minsResponse", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryImprestOrderByDate10MinsResponse")
    public String queryImprestOrderByDate10Mins(
        @WebParam(name = "in0", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        long in4,
        @WebParam(name = "in5", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in6,
        @WebParam(name = "in7", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        int in7,
        @WebParam(name = "in8", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in8,
        @WebParam(name = "in9", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in9);

    /**
     * 
     * @param in6
     * @param in5
     * @param in8
     * @param in7
     * @param in9
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
    @RequestWrapper(localName = "queryRegisterByAccount", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryRegisterByAccount")
    @ResponseWrapper(localName = "queryRegisterByAccountResponse", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryRegisterByAccountResponse")
    public String queryRegisterByAccount(
        @WebParam(name = "in0", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        int in4,
        @WebParam(name = "in5", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        int in5,
        @WebParam(name = "in6", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        int in6,
        @WebParam(name = "in7", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        int in7,
        @WebParam(name = "in8", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in8,
        @WebParam(name = "in9", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in9);

    /**
     * 
     * @param in6
     * @param in5
     * @param in8
     * @param in7
     * @param in9
     * @param in10
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
    @RequestWrapper(localName = "queryImprestBySidAndSubidByDate", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryImprestBySidAndSubidByDate")
    @ResponseWrapper(localName = "queryImprestBySidAndSubidByDateResponse", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryImprestBySidAndSubidByDateResponse")
    public String queryImprestBySidAndSubidByDate(
        @WebParam(name = "in0", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        int in4,
        @WebParam(name = "in5", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        long in5,
        @WebParam(name = "in6", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in6,
        @WebParam(name = "in7", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in7,
        @WebParam(name = "in8", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        int in8,
        @WebParam(name = "in9", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in9,
        @WebParam(name = "in10", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in10);

    /**
     * 
     * @param in6
     * @param in5
     * @param in8
     * @param in7
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
    @RequestWrapper(localName = "queryImprestOrderSum", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryImprestOrderSum")
    @ResponseWrapper(localName = "queryImprestOrderSumResponse", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryImprestOrderSumResponse")
    public String queryImprestOrderSum(
        @WebParam(name = "in0", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        long in4,
        @WebParam(name = "in5", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in6,
        @WebParam(name = "in7", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in7,
        @WebParam(name = "in8", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in8);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
    @RequestWrapper(localName = "queryIssuerList", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryIssuerList")
    @ResponseWrapper(localName = "queryIssuerListResponse", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryIssuerListResponse")
    public String queryIssuerList(
        @WebParam(name = "in0", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in4);

    /**
     * 
     * @param in6
     * @param in5
     * @param in8
     * @param in7
     * @param in9
     * @param in10
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
    @RequestWrapper(localName = "queryImprestBySubidByDate", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryImprestBySubidByDate")
    @ResponseWrapper(localName = "queryImprestBySubidByDateResponse", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryImprestBySubidByDateResponse")
    public String queryImprestBySubidByDate(
        @WebParam(name = "in0", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        int in4,
        @WebParam(name = "in5", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        long in5,
        @WebParam(name = "in6", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in6,
        @WebParam(name = "in7", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in7,
        @WebParam(name = "in8", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        int in8,
        @WebParam(name = "in9", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in9,
        @WebParam(name = "in10", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in10);

    /**
     * 
     * @param in6
     * @param in5
     * @param in8
     * @param in7
     * @param in9
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
    @RequestWrapper(localName = "queryPayOrderByDate", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryPayOrderByDate")
    @ResponseWrapper(localName = "queryPayOrderByDateResponse", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryPayOrderByDateResponse")
    public String queryPayOrderByDate(
        @WebParam(name = "in0", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        long in4,
        @WebParam(name = "in5", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in6,
        @WebParam(name = "in7", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        int in7,
        @WebParam(name = "in8", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in8,
        @WebParam(name = "in9", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in9);

    /**
     * 
     * @param in6
     * @param in5
     * @param in8
     * @param in7
     * @param in9
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
    @RequestWrapper(localName = "queryRegisterBySidByDate", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryRegisterBySidByDate")
    @ResponseWrapper(localName = "queryRegisterBySidByDateResponse", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryRegisterBySidByDateResponse")
    public String queryRegisterBySidByDate(
        @WebParam(name = "in0", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        int in4,
        @WebParam(name = "in5", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in6,
        @WebParam(name = "in7", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        int in7,
        @WebParam(name = "in8", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in8,
        @WebParam(name = "in9", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in9);

    /**
     * 
     * @param in6
     * @param in5
     * @param in8
     * @param in7
     * @param in9
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
    @RequestWrapper(localName = "queryImprestInfoByDate", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryImprestInfoByDate")
    @ResponseWrapper(localName = "queryImprestInfoByDateResponse", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryImprestInfoByDateResponse")
    public String queryImprestInfoByDate(
        @WebParam(name = "in0", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        long in4,
        @WebParam(name = "in5", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in6,
        @WebParam(name = "in7", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        int in7,
        @WebParam(name = "in8", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in8,
        @WebParam(name = "in9", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in9);

    /**
     * 
     * @param in6
     * @param in5
     * @param in8
     * @param in7
     * @param in9
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
    @RequestWrapper(localName = "queryRegisterInfoByDate", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryRegisterInfoByDate")
    @ResponseWrapper(localName = "queryRegisterInfoByDateResponse", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", className = "com.woniu.sncp.webservice.usercenter.query.QueryRegisterInfoByDateResponse")
    public String queryRegisterInfoByDate(
        @WebParam(name = "in0", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        long in4,
        @WebParam(name = "in5", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in6,
        @WebParam(name = "in7", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        int in7,
        @WebParam(name = "in8", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in8,
        @WebParam(name = "in9", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com")
        String in9);

}
