
package com.woniu.sncp.webservice.usercenter.query;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "QueryWebService", targetNamespace = "http://query.usercenter.webservice.sncp.woniu.com", wsdlLocation = "http://business.api.sandbox.wn/services/QueryWebService?wsdl")
public class QueryWebService
    extends Service
{

    private final static URL QUERYWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException QUERYWEBSERVICE_EXCEPTION;
    private final static QName QUERYWEBSERVICE_QNAME = new QName("http://query.usercenter.webservice.sncp.woniu.com", "QueryWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://business.api.sandbox.wn/services/QueryWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QUERYWEBSERVICE_WSDL_LOCATION = url;
        QUERYWEBSERVICE_EXCEPTION = e;
    }

    public QueryWebService() {
        super(__getWsdlLocation(), QUERYWEBSERVICE_QNAME);
    }

    public QueryWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUERYWEBSERVICE_QNAME, features);
    }

    public QueryWebService(URL wsdlLocation) {
        super(wsdlLocation, QUERYWEBSERVICE_QNAME);
    }

    public QueryWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUERYWEBSERVICE_QNAME, features);
    }

    public QueryWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns QueryWebServicePortType
     */
    @WebEndpoint(name = "QueryWebServiceHttpPort")
    public QueryWebServicePortType getQueryWebServiceHttpPort() {
        return super.getPort(new QName("http://query.usercenter.webservice.sncp.woniu.com", "QueryWebServiceHttpPort"), QueryWebServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryWebServicePortType
     */
    @WebEndpoint(name = "QueryWebServiceHttpPort")
    public QueryWebServicePortType getQueryWebServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://query.usercenter.webservice.sncp.woniu.com", "QueryWebServiceHttpPort"), QueryWebServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUERYWEBSERVICE_EXCEPTION!= null) {
            throw QUERYWEBSERVICE_EXCEPTION;
        }
        return QUERYWEBSERVICE_WSDL_LOCATION;
    }

}
